# Create humidistat sensors (https://github.com/basschipper/homeassistant-generic-hygrostat)
- platform: generic_hygrostat
  name: Master Bathroom Hygrostat
  unique_id: master_bathroom_hygrostat
  sensor: sensor.master_bathroom_weather_humidity
  max_on_time: 1800 # Optional safety max on time in seconds. Default = 7200 seconds
  min_humidity: 55

- platform: generic_hygrostat
  name: Guest Bathroom Hygrostat
  unique_id: guest_bathroom_hygrostat
  sensor: sensor.guest_bathroom_weather_humidity
  max_on_time: 1800
  delta_trigger: 6
  min_humidity: 55

- platform: generic_hygrostat
  name: Kids Bathroom Hygrostat
  unique_id: kids_bathroom_hygrostat
  sensor: sensor.kids_bathroom_weather_humidity
  max_on_time: 1800
  min_humidity: 55

# https://diyfuturism.com/index.php/2017/12/29/useful-sensor-bayesian-sleep-detection-in-home-assistant/
- platform: bayesian
  name: "Bayesian Sleep Sensor"
  unique_id: "e5d4e97d-1b13-4bbb-8e0a-4efb1e95137a" # generated on https://www.uuidgenerator.net/
  prior: 0.29 # I spend 7 hours a day in bed (7hr/24hr)
  probability_threshold: 0.85 # I am going to be using this sensor to turn out the lights so I only want to to activate when I am sure
  observations:
    # Evening
    - platform: state
      entity_id: sun.sun
      prob_given_true: 0.90 # Assuming the bayesian binary_sensor is true, the probability the entity state is occurring.
      prob_given_false: 0.45 # Assuming the bayesian binary_sensor is false the probability the entity state is occurring.
      to_state: 'below_horizon'
    # No motion downstairs
    - platform: state
      entity_id: binary_sensor.downstairs_motion_any
      prob_given_true: 0.85
      prob_given_false: 0.75
      to_state: 'on'
    # No recent activity in Master Bathroom
    - platform: template
      prob_given_true: 0.85
      prob_given_false: 0.35
      value_template: "{{ states.binary_sensor.master_bathroom_motion_any.last_updated|default(today_at('00:00')) + timedelta(minutes=states('input_number.inactivity_timeout_medium')|int) < utcnow() }}"
    # All Master Suite Lights off
    - platform: template
      prob_given_true: 0.95
      prob_given_false: 0.75
      value_template: "{{ expand(area_entities('master_bedroom') + area_entities('master_bathroom'))|selectattr('domain', 'in', 'light')|selectattr('state', 'eq', 'on')|list|length == 0 }}"
    # TV Off
    - platform: template
      prob_given_true: 0.95
      prob_given_false: 0.20
      value_template: "{{ not is_state('media_player.samsung_un55h7100', 'on') }}"
    # Presence
    - entity_id: person.james
      prob_given_true: 0.99
      prob_given_false: 0.30
      platform: state
      to_state: 'home'
    # Phone charging
    - platform: template
      prob_given_true: 0.80
      prob_given_false: 0.25
      value_template: "{{ states('sensor.james_iphone_battery_state')|lower in ['charging', 'full'] }}"
    # Phone activity
    - entity_id: sensor.james_iphone_activity
      prob_given_true: 0.80
      prob_given_false: 0.35
      platform: state
      to_state: 'stationary'
