
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

homeassistant:
  customize: !include customize.yaml
  media_dirs:
    sounds: /config/www/sounds
    images: /config/www/images

# Include themes directory
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js

lovelace:
  mode: storage
  dashboards:
    lovelace-yaml:
      mode: yaml
      title: Dashboard
      icon: mdi:script
      show_in_sidebar: true
      filename: ui-lovelace.yaml
    keener-yaml:
      mode: yaml
      title: Keener
      icon: mdi:home
      show_in_sidebar: true
      filename: ui-keener.yaml

logger:
  default: warning
  logs: {}

http:
  use_x_forwarded_for: true
  trusted_proxies: !secret trusted_proxies

sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
light: !include lights.yaml
fan: !include fans.yaml
template: !include templates.yaml
# zwave: !include zwave.yaml
zha: !include zha.yaml
homekit: !include homekit.yaml
cover: !include cover.yaml
# mqtt: !include mqtt.yaml

# Use camera plugin for forcast/doplar images
camera:
  - platform: local_file
    name: Weather Local Doplar
    file_path: /config/www/camera.weather_local_doplar
  - platform: local_file
    name: Weather Local Forecast
    file_path: /config/www/camera.weather_local_forecast
  - platform: local_file
    name: Weather NOAA US East Coast
    file_path: /config/www/camera.weather_noaa_us_east_coast
  - platform: local_file
    name: Weather NOAA US Southeast
    file_path: /config/www/camera.weather_noaa_us_southeast
  - platform: local_file
    name: Weather NOAA US Continent
    file_path: /config/www/camera.weather_noaa_us_continent

# This stops working in version 2024.10.0. Please address before upgrading
# downloader:
#   download_dir: www

input_text: !include input_text.yaml
input_number: !include input_number.yaml
# input_datetime: !include input_datetime.yaml

# Enable/disable browser mod plugin
# browser_mod:

# Illuminance configuration
# https://github.com/pnbruckner/ha-illuminance
illuminance: !include illuminance.yaml
