# Combine multiple lights into one
- platform: group
  name: Living Room Bookshelf
  entities:
    - light.living_room_bookshelf_left
    - light.living_room_bookshelf_right

- platform: group
  name: 'Back Deck Lights'
  unique_id: light.back_deck_lights
  entities:
    - light.deck_rail_light
    - light.deck_step_light

# Convert switches to a light
- platform: switch
  name: Back Door Light
  entity_id: switch.back_door_light_switch
- platform: switch
  name: Back Spot Light
  entity_id: switch.back_spot_light_switch
- platform: switch
  name: Entryway Door Light
  entity_id: switch.entryway_door_light_switch
- platform: switch
  name: Entryway Hall Light
  entity_id: switch.entryway_hall_light_switch
- platform: switch
  name: Front Door Light
  entity_id: switch.front_door_light_switch
- platform: switch
  name: Front Spot Light
  entity_id: switch.front_spot_light_switch
- platform: switch
  name: Garage Exterior Light
  entity_id: switch.garage_exterior_light_switch
- platform: switch
  name: Garage Light
  entity_id: switch.garage_light_switch
- platform: switch
  name: Garage Work Light
  entity_id: switch.garage_work_light_switch
- platform: switch
  name: Guest Bathroom Light
  entity_id: switch.guest_bathroom_light_switch
- platform: switch
  name: Guest Room Fan Light
  entity_id: switch.guest_room_fan_light_switch
- platform: switch
  name: Guest Room Nightstand
  entity_id: switch.guest_room_nightstand_switch
- platform: switch
  name: "Henry's Room Fan Light"
  entity_id: switch.henrys_room_fan_light_switch
- platform: switch
  name: Kids Bathroom Light
  entity_id: switch.kids_bathroom_light_switch
- platform: switch
  name: Laundry Room Light
  entity_id: switch.laundry_room_light_switch
- platform: switch
  name: Living Room Fan Light
  entity_id: switch.living_room_fan_light_switch
- platform: switch
  name: Master Bathroom Light
  entity_id: switch.master_bathroom_light_switch
- platform: switch
  name: Master Bathroom Shower Light
  entity_id: switch.master_bathroom_shower_light_switch
- platform: switch
  name: Master Bedroom Fan Light
  entity_id: switch.master_bedroom_fan_light_switch
- platform: switch
  name: Master Bedroom Nightstand
  entity_id: switch.master_bedroom_nightstand_switch
- platform: switch
  name: Mudroom Light
  entity_id: switch.mudroom_light_switch
- platform: switch
  name: Sunroom Fan Light
  entity_id: switch.sunroom_fan_light_switch
- platform: switch
  name: "William's Room Fan Light"
  entity_id: switch.williams_room_fan_light_switch
- platform: switch
  name: "Shannon's Closet Light"
  entity_id: switch.shannons_closet_light_switch
- platform: switch
  name: Master Bathroom Toilet Light
  entity_id: switch.master_bathroom_toilet_light_switch
- platform: switch
  name: Powder Room Light
  entity_id: switch.powder_room_light_switch
- platform: switch
  name: Kids Bathroom Shower Light
  entity_id: switch.kids_bathroom_shower_light_switch_0
- platform: switch
  name: Stairway Light
  entity_id: switch.stairway_light_switch
- platform: switch
  name: Upstairs Hallway Light
  entity_id: switch.upstairs_hallway_light_switch
- platform: switch
  name: "William's Closet Light"
  entity_id: switch.williams_closet_light_switch
- platform: switch
  name: "James' Closet Light"
  entity_id: switch.james_closet_light_switch
- platform: switch
  name: "Guest Room Closet Light"
  entity_id: switch.guest_room_closet_light_switch
- platform: switch
  name: "Attic Light"
  entity_id: switch.attic_light_switch
- platform: switch
  name: "Attic Stairway Light"
  entity_id: switch.attic_stairway_light_switch
#- platform: switch
#  name: "Living Room Christmas Tree"
#  entity_id: switch.living_room_plug_switch
#- platform: switch
#  name: "Dining Room Christmas Tree"
#  entity_id: switch.dining_room_plug
